# Generated by Django 6.0.3 on 2026-03-17 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creation date"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Company name"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_department_related",
                        to="auth.group",
                        verbose_name="Department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner_related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creation date"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Title / Position",
                    ),
                ),
                ("email", models.CharField(blank=True, default="", max_length=200)),
                ("phone", models.CharField(blank=True, default="", max_length=100)),
                ("city_name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("website", models.URLField(blank=True, default="", unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("disqualified", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_department_related",
                        to="auth.group",
                        verbose_name="Department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner_related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creation date"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Qualified", "Qualified"),
                            ("Ready to Connect", "Ready To Connect"),
                            ("Pending", "Pending"),
                            ("Connected", "Connected"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Qualified",
                        max_length=20,
                    ),
                ),
                (
                    "closing_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Disqualified", "Disqualified"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("next_step_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("ticket", models.CharField(default="", max_length=16, unique=True)),
                ("win_closing_date", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="crm.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_department_related",
                        to="auth.group",
                        verbose_name="Department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner_related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
            },
        ),
    ]
